language: r
matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel
dist: trusty
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg --allow-unauthenticated

notifications:
  email:
    on_success: always
    on_failure: always

env:
  global:
  - secure: kMErjW2aR1O7j6AqGgCFd0UROIHPwADKehdzqY8INqdzah44UND4gOV1DpOPoB+x6NEKtLEiVNL/1AhxxBHTClv1ZR88qe4gfNDLhsAAN63JM2RVFf5qXgnMdBjgL/XS9PBJ/f0eIk85lkuLmZ0RTIiiu/umsqtzanUQ27tKHbsC/LUJrKwVDZkUt1/s6Roq8vfFaD/r7Iwh5kk5Dypqz6Cr6F75dRX7V7YicxMKoFJx2rlkx8n6WYqdxXsFDptKfl9pNiUDuGrUqqH2OwQ2nwOF9j3rjpeG+TdrDvMQ+ZGxhtHb9/ekin9UVUbWiZH+DAjlhWPjWk2C2yTqGZ9q6FYQu3UWujWPi5I0o6WNtGt9tBRZtkxwfz+xT6xu+prVc+YTzVowlJhxHg+XhCjUZGPQnkaTTMrjz27BAMP/xA7BvjFsKcBCIOkF7RJfGYQdFyBk/eSBvslRunQgBYnmUM5Z1sr0GTEdi6RjHnTZmI18H+oAsNgb9JdSv2/4Cw0Fd/Sy25MwcIfMn1gQrNVI9Qbj8YLWP8VqsRFRSP53NYdZqoEQ1muIbDwm94uu6IIDqzz91NRYd1QCDXpPpCOE4+XoUVJyX73/LaHzhVPel2M3JzkVZu6jNJNfVO4G1KGJLGhUjJZSkt9iax2l0uWqU2yg9GDbWuan3rXISRYUpc8=
  - secure: s30xpRfOtWJQ7bfRFYh3DZy1UO1I5IXQKOL+HHiWlYZOqfn+30fMF1Uoycg/FV0DL16L1KAWjFaAWQwOmQSP8fRKJTeClKA20UUZ/G1dnnmvP8ilA3WpVivkeYFs5z4CbNFAMzzjE9OEqylvViFqtmuBQVwTSch2eINTXZP+XKazTQ4MI1RUd7C5VQ9hw6/y+SsqFAxsFFJNBcTs69eOxScZd3sbNmSrCFnA8wZgPo0RV97LzcqhKV3CwwqrAJOmKcAEg9JJPCkzqclAfS7+H4X7co24WlvbhqsCr+D4aPaGdYbLlTKkKK6Nk5BXbbou5zgQyjcQlD7InXb9IMqc46nlL/6G3yZAJm10keaZJckQIpMXHV+lWT7XK0MdjKlgjvZMYqBHMeC8xdHouajNOUMbAqJXQekLVZXIrpOvPpRYw+BREJGCtaVerqv4CAfreP/BDFsvPcbKuSvus30Xs7ZJsvWU5VQ8aOT3MhPA2kJfk83hWd2ZYJAKhqiT0GIn4FewGDeQqh25MNo2sJ7o1iXlL7NaEh4L68yDqHS5GD5BLCL2z5iPZlj/ge5JHzUgDiolzbPsDPnX0RllaBQ7wa1JvZ6FruJ/vcGHXRiIpJSTuqxT2J8g/AmJC3pOmzaG+wXYK+7lE7fVujlQX14vJGv7j/xOunizJsIeoghaqE4=
  - secure: rCyDCkGAcfE+ixTZbVx2w1plKWPZckGCFGr6Xxyi0y1rrmuMP7tn3zKpmQdAdRcVdg3p94fD11H8rNyL7M2g+pjkJ8lqif6s6L/uKUO2JFSSQbJU+clFJEYiHh7gsNok53bJSqhrIud5/WIKD1uYc3VstfqM1dpLYz5w3mIGtrVOzxnnZnmNAT3fksovrpbGzM9gLSR7vgwJ/27civNtHDjJ+sJugTdjGIFw1FfinvBw5vVuywKrQM2xk973i05puctlL7iZUH2fykiJTWs1TlGzEXNVT/A4KmuujLT27Ltz08R8QSJqz3MCaO70CFFTkWj4zkQPiP1cUQaRLhP8zywKcGbfWyF/ZSbuQVJ9Ot0WuW/GMIA5Lb9h/B5/ccfWaaQ1mLtepY4ZnGJdE98KGp7o9fPTHKA7qZxdo1ecikRgo0QhhMtsc4iDA1JcrwbZewVmIn/590O1E7GAeIRtv4C2k21t77cZHVH6ELqnZm9kE2JfQBbD5Q/xLKtBJxFAdYNbR7ebS5soMVOYVox30BlpyveSj5HwhiwsqtfscX3k1Rsp7vAYZ+DpIi4mmL7T92OTzA1aY74C2LvMPW/7vYPX2CrN8nPwPhQJYphj60cx67Kec3u8yezcvALMOws+mwPGsQq8+NHKmyixLhsCCA0HZiTwe+sLaV+V74s0hhU=
